version: "3"

services:
  proxy-server:
    image: sameersbn/squid:3.5.27-2
    ports:
      - "3128:3128"
    volumes:
      - ../common_conf/squid.conf:/etc/squid/squid.conf
      - /srv/docker/squid/cache:/var/spool/squid


  apt-add-repository:
    depends_on:
      - proxy-server
    build: .
    volumes:
      - ../../../../swpro:/home/user/swpro

    user: user:user
    command: >
      bash -c "
      cd swpro
      && sudo chown -R user:user . 
      && sudo bin/swpro install
      && sudo swpro set apt-add-repository http://proxy-server:3128
      && sudo apt-add-repository  ppa:teejee2008/timeshift
      && sudo swpro disable apt-add-repository
      && sudo apt-add-repository  ppa:teejee2008/timeshift
      && sudo swpro enable apt-add-repository
      && sudo apt-add-repository  ppa:teejee2008/timeshift
      "