name: Crystal CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Bulid
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bin
        path: ./

  docker-test:
    name: test by docker container
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download bin
      uses: actions/download-artifact@v2
      with:
        name: bin
    - name: on docker test
      run: make test
  
  release:
    name: release result
    needs: docker-test
    runs-on: ubuntu-latest
    steps:
    - name: Download bin
      uses: actions/download-artifact@v2
      with:
        name: bin
    - name: on docker test
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1.0
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./swpro.zip
        asset_name: swpro.zip
        asset_content_type: application/zip
